### ISSUE TITLE
Gazpar no longer works since the Home Assistant 2021.7.0 update.

### ISSUE THREAD

**Issue by sidwin9** [cyprieng/gazpar-home-assistant#10]
Hey,

Gazpar no longer works since the Home Assistant 2021.7.0 update.

**Comment by dckiller51** [comment]
Slt, regarde dans Pull requests j'ai mis à jour. 
Par contre avant 
1) désactive le sensor
2) redemarre hassio
3) modifie le manifest.json
```
{
  "domain": "gazpar",
  "name": "Gazpar",
  "documentation": "https://github.com/cyprieng/gazpar-home-assistant",
  "issue_tracker": "https://github.com/cyprieng/gazpar-home-assistant/issues",
  "dependencies": [],
  "version": "0.0.3",
  "codeowners": ["cyprieng"],
  "requirements": ["requests==2.25.1", "lxml==4.6.3"],
  "iot_class": "cloud_polling"
}
```
4) Réactive ton sensor
5) redémarre

Normalement cela devrait fonctionner. C'est le cas chez moi.

**Comment by sidwin9** [comment]
Impec, ça fonctionne mais j'ai également mis à jour le fichier __init__.py

Merci.

**Comment by dckiller51** [comment]
Super je me permets de fermer.
