### ISSUE TITLE
Add volume (m3) sensors

### ISSUE THREAD

**Issue by Mincka** [cyprieng/gazpar-home-assistant#15]
The upcoming version of HA will support gaz but it looks like they plan to require m3 as measurement unit...
![image](https://user-images.githubusercontent.com/6184289/129902562-5bc86520-9c26-47c5-b1dd-1ac6531fcf6f.png)

Volume makes sense for exact consumption but kWh is more useful for alignment and price mapping. I asked support for both on Twitter.

Anyway, since the volume is also available on the GRDF website, it could be great to get it with additional sensors.
I had a quick look and there's minor changes between the requests for kWh and m3 for the payload.

I may propose a PR for this.

**Comment by cyprieng** [comment]
I added m3 sensors, it works for month period but not for day period (it returns months instead of days). I copy/paste the request from grdf but it doesn't work.

I will let you know if I find a fix.
