### ISSUE TITLE
'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by roncamma** [cyprieng/gazpar-home-assistant#2]
Hello Cyrpien,

I installed your component in my Home Assistant with rights credentials.
But I obtain this error in Hass servers logs.

Can you take a look ?

Thank you for your work !

Clément.

```
Logger: custom_components.gazpar.sensor
Source: custom_components/gazpar/sensor.py:113
Integration: gazpar
First occurred: 12:35:57 PM (1 occurrences)
Last logged: 12:35:57 PM
Failed to query Gazpar library with exception : Traceback (most recent call last): File "/config/custom_components/gazpar/sensor.py", line 89, in update_gazpar_data data = gazpar.get_data_per_day(session, File "/config/custom_components/gazpar/gazpar.py", line 139, in get_data_per_day return _get_data(session, 'Jour', start_date, end_date) File "/config/custom_components/gazpar/gazpar.py", line 306, in _get_data d = md.group(1) AttributeError: 'NoneType' object has no attribute 'group' 
```

**Comment by cyprieng** [comment]
Hello,

I am able to reproduce this issue randomly.

Some times Grdf api return something like this without any expected data:
```
<partial-response>
    <changes>
        <update id="javax.faces.ViewState">...</update>
    </changes>
</partial-response>
```

I check how I can fix this, I will let you know if I found something.

**Comment by roncamma** [comment]
Yes, your plugin still retrieve some data.

But, it is not the last day kWh but the day before.
For exemple I have today (13th) the data of the 11th. (correct timestamp)
![image](https://user-images.githubusercontent.com/19478789/99067635-5758ba00-25ab-11eb-9e45-aae14f249b81.png)

But for the month data, it is not the last month, it is the currend month no ?

Thanks !

PS : You prefer continue in English ? (Because Gazpar is only in France :D)

**Comment by cyprieng** [comment]
Effectivement on peut continuer en français 😄 

Oui c'est effectivement le mois en cours pas le précédent, j'ai corrigé la doc.

Pour le décalage c'est parce que les données de GRDF ont un retard en général de deux jours.

**Comment by lorisbc** [comment]
Bonjour, 
pour éviter le cas où GRDF ne renvoie rien, il est peut être possible de jouer sur le `@retry`.
Sur le `_get_data` on a `tries=4, delay=3, backoff=2`,  donc on réessaye après 3 secondes, 6s, 12s, et 24s si je comprends bien. 
Si le soucis vient du côté de GRDF, il faudrait peut-être augmenter ces délais, surtout que l'on n'est pas pressé d'avoir les données comme on veut la conso journalière.

Peut être mettre `@retry(Exception, tries=4, delay=60, backoff=3)`, ça donnerait 1mn, 3mn, 9mn, 27mn, ça laisse le temps aux serveurs de GRDF d'être up.

**Comment by cyprieng** [comment]
Bonjour @lorisbc 

Effectivement le retry était un peu rapide, je viens de mettre à jour.

Merci

**Comment by roncamma** [comment]
La conso de la veille apparait sur le site grdf.fr qu'en milieu de journée en effet.
Logique d'avoir encore la conso d'il y a 2 jours donc le matin.

Le retry est pas mal. Je ne vois plus l'erreur.
D'ailleurs lors du restart d'home assistant, la conso est systematiquement en unknown.
Peut être rajouter un délai de quelques secondes avant le premier try ?

**Comment by lorisbc** [comment]
Plus de soucis, même au démarrage, j'ai redémarré plusieurs fois ces derniers jours sans soucis. 😄
