### ISSUE TITLE
Depuis le 23 novembre GRDF a modifié le site Web. 

### ISSUE THREAD

**Issue by pbranly** [cyprieng/gazpar-home-assistant#20]
L’intégration de fonctionne plus depuis la modification du site web de GRDF

**Comment by lorisbc** [comment]
Sur le nouveau site, une fois connecté, on peut récupérer par 'API' nos données journalières entre deux dates comme ça : 
`https://monespace.grdf.fr/api/e-conso/pce/consommation/informatives?dateDebut=2019-11-21&dateFin=2021-11-24&pceList%5B%5D=[PCE_NUMBER]"`

La réponse est du json, ça sera plus simple et plus fiable que avant :)

**Comment by olivier2591** [comment]
bonjour, 
novice dans le domaine pourriez vous expliquer le fichier a modifier ? a moins qu'une mise a jour ne soit prévue ?

**Comment by cyprieng** [comment]
Bonjour,

Je suis en train de regarder pour mettre le module à jour, j'espère finir d'ici demain.
Je vous tiens au courant.

**Comment by olivier2591** [comment]
un grand merci pour votre réactivité ;-)

**Comment by Sailman83** [comment]
Bonjour @cyprieng ,

Cette mise a jours comprendra les autres problèmes que j'ai remonté ?

Cordialement

**Comment by cyprieng** [comment]
Je viens de publier une nouvelle version. Celle-ci introduit un changement majeur, il n'y a plus qu'un seul sensor: l'index de consommation en kwh, le reste des données pouvant être récupéré via le dashboard energy de home assistant.
J'espère qu'on aura une meilleure précision des données avec cette nouvelle version 🤞

**Comment by lorisbc** [comment]
Merci pour ta réactivité ! J'ai configuré et reçu de la data. On verra dans les prochains jours le dashboard energy :)

**Comment by olivier2591** [comment]
J'ai mis à jour. 
Bien penser à rajouter le numéro PCE dans la config du capteur.
Toutefois le résultat ne correspond pas à une consommation. j'obtient la valeur de 536 (kWh??). Beaucoup pour une journée, et je n'ai pas un château !! ;-)
avec le lien de lorisbc, voici ce que j'ai : 
23","indexDebut":536,"indexFin":543,"volumeBrutConsomme":7,"energieConsomme":74,"pcs":null,"volumeConverti":null,"pta":null,"natureReleve":"Informative Journalier","qualificationReleve":"Mesur\u00e9","status":null,"coeffConversion":null,"frequenceReleve":null,"temperature":null}],"frequence":null}}

Pour le 23/11 ma conso est de 74kWh. ou 7m3. 
On dirai que la valeur du capteur correspond à l'index de départ de la journée.

Avez vous de bonne valeur ????

**Comment by lorisbc** [comment]
C'est effectivement l'index de consommation totale.
Grâce au nouveau système de home assistant pour l'énergie, l'index total est une bonne métrique. En fait, home assistant a besoin d'une valeur qui ne fait que incrémenter et c'est home assistant qui se charge de calculer la consommation journalière en faisant le delta. 

Dans les state attributes du nouveau sensor, on voit que @cyprieng a bien configuré le sensor pour utiliser l'énergie et que c'est un total qui augmente ;)  

```
state_class: total_increasing
unit_of_measurement: kWh
friendly_name: Gazpar kwh
icon: mdi:fire
device_class: energy
```

**Comment by olivier2591** [comment]
ha ok donc d'ici 1 a deux jours HA va s'occuper de la soustraction.
Toutefois la valeur de 536 de l'index ce sont des m3 non ? et de ces m3 multiplié par un facteur de conversion on obtient des kWh.

**Comment by olivier2591** [comment]
Première remontée d’information et la valeur correspond  à des m3.
7 dans mon cas (543-536) voir mon post précédent.
Il faudrait changer l’unité du sensor ou récupérer la valeur de la consommation.

**Comment by chris60600** [comment]
Je confirme ce que @olivier2591 a commenté la valeur d'index correspond à des M3. 
Dans la feuille EXCEL les entêtes de colonnes sont :  
- Index de début de période (m3)  
- Index de fin de période (m3) 
- Volume consommé (m3) 
- Energie consommée (kWh)

en ligne 11 de sensor.py au lieu de 
```
ENERGY_KILO_WATT_HOUR, DEVICE_CLASS_ENERGY
```
```
VOLUME_CUBIC_METERS, DEVICE_CLASS_GAS
```
Par contre si l'on pouvait ajouter un sensor supplémentaire avec la valeur du jour en KWh ça serait top (ou un attribut  du sensor)

**Comment by calouis** [comment]
Bonjour
Petite question de débutant, comment fait-on avec l'ancienne version installée ? Juste désactiver les 2 automations ?

**Comment by pbranly** [comment]
Si elle a été mise via HACS, il suffit de la recharge et de modifier le sensor .
Par contre, j’ai du redémarrer HA à la hache car il n’aimait pas la modif de sensor !
Ensuite il faut supprimer l’utilisation éventuelle des anciens sensors 
Phil

**Comment by calouis** [comment]
Avant de faire une bêtise, doit-on supprimer dans _configuration.yaml_ ceci : 
`sensor:
  - platform: command_line
    name: GRDF consommation gaz
    command: "/config/gazpar/gazpar_ha.sh sensor"
    scan_interval: 100000000
    unit_of_measurement: "kWh"
    json_attributes:
      - conso_m3
      - index_m3
      - date
      - log
    value_template: '{{ value_json.conso }}'

# ce Sensor permettra d'ajouter la consommation au Tableau de bord Energie 
template:
- sensor:
    name: "Gas consumption index (m³)"
    unit_of_measurement: "m³"
    device_class: "gas"
    state_class: "total_increasing"
    state: "{{ state_attr('sensor.grdf_consommation_gaz', 'index_m3') }}"

# ce Sensor est optionnel
  - sensor:
    name: "GRDF consommation gaz (m³)"
    unit_of_measurement: "m³"
    device_class: "gas"
    state: "{{ state_attr('sensor.grdf_consommation_gaz', 'conso_m3') }}"

shell_command:
    grdf_get_data: '/config/gazpar/gazpar_ha.sh fetch  {{ states("input_text.grdf_user") | base64_encode }} {{ states("input_text.grdf_pwd") | base64_encode }}  {{ states("input_text.grdf_pce") }}'
    grdf_delete_data: '/config/gazpar/gazpar_ha.sh delete'

input_text:
  grdf_user:
    initial: !secret grdf_user
  grdf_pwd:
    initial: !secret grdf_pwd
  grdf_pce:
    initial: !secret grdf_pce`
ma source étant : https://githubmemory.com/repo/frtz13/homeassistant_gazpar_cl_sensor

Désolé pour ces questions qui doivent vous paraître évidente...

**Comment by pbranly** [comment]
Je pense que vous avez une vieille configuration 
Le seul fichier pour faire fonctionner est décrit dans la documentation 

Add this to your configuration.yaml:

sensor:
  - platform: gazpar
    username: !secret gazpar.username
    password: !secret gazpar.password
    pce: 1234567890  # PCE identifier (can be found on grdf.fr)
This will create a kwh index sensor that can be used in HA energy.
Ensuite vous faites ce que vous voulez du sensor créé en kWh
Philippe

**Comment by max5962** [comment]
hello, @cyprieng ,

j'ai update avec le changement de configuration, il y a quelques jours ( le jour du patch ) 
Cela m'a créé un nouveau sensor : sensor.gazpar_kwh
![image](https://user-images.githubusercontent.com/34659571/143853642-f9b5c9c7-83fe-49eb-bea5-89d3a6d7fc46.png)


Mais aucune update depuis.
Une idée ?

**Comment by pbranly** [comment]
Il n'y a pas de mise à jour sur le site GRDF depuis le 23
Phil

**Comment by max5962** [comment]
> Il n'y a pas de mise à jour sur le site GRDF depuis le 23 Phil

Effectivement ! c'est "normal" ?

**Comment by pbranly** [comment]
Ce qui est inquiétant c'est que EDF a des valeurs plus récentes 
( je suis chez EDF en gaz)
Donc il semblerait qu'il y ait une autre source de données 
Inquiétant .... oui !
Phil

**Comment by max5962** [comment]
ça sent surtout que la remontée est OK, mais que la MAJ du site "customer" ne l'est plus. Surtout quand on voit que le Site à été MAJ récemment.
Donc je m'inquièterait pas plus que ça finalement :)

**Comment by cyprieng** [comment]
Je viens de mettre à jour pour que la consommation soit en m3 au lieu de kwh, je vais voir comment je peux récupérer la conso en kwh.

**Comment by cyprieng** [comment]
Je viens d'ajouter un index en kwh en me basant sur la consommation depuis le 1 janvier. On verra si cette méthode est fiable.

**Comment by chris60600** [comment]
> Je viens d'ajouter un index en kwh en me basant sur la consommation depuis le 1 janvier. On verra si cette méthode est fiable.

Il ne me parait pas bon. En fait tout dépend de ce que tu veux obtenir. Les kWh sont calculés a partir d'un coefficient qui varie quelque peu mais qui pour moi est entre 11.08 et 11,14. En gros mon m3 représente ~ 11 kWh donc si je prend mon index de 1670 m3 je devrais avoir 18370 kWh et j'ai 9067.  Je ne sais pas si l'index en kWh est vraiment intéressant. Surtout que que pour avoir le coût il faut le ramener au mois (ou au jour) et même la mon prix du kWh varie d'un mois sur l'autre (selon ma dernière facture). La conso mensuelle en kWh, présente dans le json me parait intéressante. Peux être pouvoir paramétrer le coefficient de conversion m3/kWh (je ne sais pas si c'est le même pour tout le monde)
Merci en tout cas pour le travail @cyprieng 
Au fait les dernières valeurs par l'API publiées ou informatives sont bloquées au 25/11

**Comment by cyprieng** [comment]
@chris60600 pour info je ne fais aucune conversion entre m3 et kwh, je prend directement la valeur en kwh que grdf me fournit pour chaque jour et j'additionne, de mon côté ça me donne bien la même valeur que sur le site de grdf. La différence est surement dû au fait que l'index en kwh est borné au début de l'année alors que l'index en m3 ne l'est pas, donc il n'y a pas de corrélation entre les deux index.

En tout cas oui aucune nouvelle donnée sur le site de grdf depuis quelques jours, pas très pratique pour tester...

**Comment by chris60600** [comment]
>  La différence est surement dû au fait que l'index en kwh est borné au début de l'année alors que l'index en m3 ne l'est pas, donc il n'y a pas de corrélation entre les deux index.

Effectivement l'index en m3 correspond Il me semble au nombre de m3 consommés depuis l'installation du compteur alors que le calcul sur l'année est borné entre la date du jour et le début de l'année en cours, ce qui va a mon avis poser un problème en début de l'année prochaine, tout au moins si l'on veut un index qui augmente sans repasser a zero. Après l'index en m3 est directement intégrable dans le module energy de HA (après la correction #21 ) et pour l'index en kWh j'ai créé un template qui multiplie par un coefficient l'index m3.  Après moi c'est mon besoin et je ne connais pas les autres besoins si ce n'est avoir le prix calculé, car pour le coup c'est bien le kwh que l'on paye !

En tout cas merci pour le développement et le temps passé

**Comment by lorisbc** [comment]
GRDF a fixé la remonté de donnée on dirait. J'ai des valeurs sur mon espace client et l'intégration dans home assistant commence à remonter des données.
