### ISSUE TITLE
Temporalité des remontées des données ? Plus rien depuis 3 jours

### ISSUE THREAD

**Issue by Doctor-Who** [cyprieng/gazpar-home-assistant#27]
Bonjour,

Un grand merci pour cette intégration très pratique et très simple d'installation pour Home Assistant.
Je l'ai installé lundi et j'ai bien eu des stats les 5 et 6 avril mais depuis plus rien.
Pas de problème sur les logs pourtant.
Une idée ?

**Comment by pbranly** [comment]
Bonjour 
Regardez si vous avez des données sur grdf.
De mon côté je n'ai plus rien depuis le 4.
Donc pas de données non plus avec l'appli 
Cdlt
Philippe

**Comment by Doctor-Who** [comment]
Bonsoir,
J'aurai du vérifier cela avant de vous ennuyer, effectivement, depuis le 06/04 plus de données sur mon espace grdf.
Je clôture l'issue et vous remercie pour ce dev opensource :) 
Bonne continuation
