### ISSUE TITLE
Plus aucune donnée n'est reçu par Home Assistant

### ISSUE THREAD

**Issue by sidwin9** [cyprieng/gazpar-home-assistant#30]
Depuis 3 semaine environ, mon Home Assistant ne reçoi aucune donnée. Les paramétrages sont correct, je n'est aucun message d'erreur dans les journaux et les données sont à jour sur le site de GRDF.

**Comment by pbranly** [comment]
Bonsoir
Le package de cyprien a t il été upgradé depuis la modification de GRDF ?
Sinon alors pas de solution 
Si oui avez vous mis à jour votre package ?
Phil

**Comment by sidwin9** [comment]
Bonjour,

J'ai la dernière version installée.

**Comment by pbranly** [comment]
Je suis allé voir le GitHub de cyprien. J’ai peur qu’il n’ait pas modifié son code depuis un moment . Donc il ne doit plus fonctionner .
Je te conseille de faire une issue sur son GitHub 
Perso j’utilise mon code sur base du moteur de ssenart. Et lui a modifié récemment

**Comment by cyprieng** [comment]
Je viens de mettre à jour le module, ça devrait de nouveau fonctionner.

Tenez moi au courant si vous rencontrez encore des soucis.
