### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'gazpar'

### ISSUE THREAD

**Issue by pbranly** [cyprieng/gazpar-home-assistant#4]
Hi
Votre programme fonctionne très bien 
Par contre j’ai eu cette erreur dans les logs
No 'version' key in the manifest file for custom integration 'gazpar'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'gazpar
cdlt
Philippe

**Comment by pbranly** [comment]
Hello in English in case of …
Please take care of this issue as it is in my logs everyday 
Regard
Philippe

**Comment by pbranly** [comment]
Kind remember

**Comment by pbranly** [comment]
Hi
I just changed the file ( by hand) with the new content and it seems that there is not anymore any error
Please push the change officially 
Regards
Philippe

**Comment by cyprieng** [comment]
Fix by #5

**Comment by pbranly** [comment]
Hi Cyprien
Closed ok but will you change the file and update the GitHub ?
Phil

Envoyé depuis mon IPhone SE 2020
