### ISSUE TITLE
Log error 

### ISSUE THREAD

**Issue by pbranly** [cyprieng/gazpar-home-assistant#6]
Hi, I also have a lot of errors that seem and come from gazpar 

Logger: custom_components.gazpar.sensor
Source: custom_components/gazpar/sensor.py:119 
Integration: gazpar 
First occurred: 13:55:42 (1 occurrences) 
Last logged: 13:55:42

Failed to query Gazpar library with exception : Traceback (most recent call last): File "/config/custom_components/gazpar/sensor.py", line 96, in update_gazpar_data data = [d for d in data if File "/config/custom_components/gazpar/sensor.py", line 97, in <listcomp> datetime.strptime(d['time'], '%d/%m/%Y') >= datetime.now().replace(day=1, hour=0, minute=0, File "/usr/local/lib/python3.8/_strptime.py", line 568, in _strptime_datetime tt, fraction, gmtoff_fraction = _strptime(data_string, format) File "/usr/local/lib/python3.8/_strptime.py", line 349, in _strptime raise ValueError("time data %r does not match format %r" % ValueError: time data '01/2021' does not match format '%d/%m/%Y'
Regards
Philippe

**Comment by cinaxx** [comment]
Hello 
I have the same issue and the same logs too

Regards
/Jordan

**Comment by cinaxx** [comment]
Up this morning! 
yesterday when i logged in there was no data so i think the problem was here 
/Jordan
